language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
- echo "skipping tests"

deploy:
  provider: pypi
  skip_existing: true
  user: "jaj"
  password:
    secure: aOZOzjB8iXA5n03sRnLSEc3UBriW6o5oz+O39kHWld3Qcc8JGfvUWpvIouBCh/WynAORvDsY+JMRLHuLSY4dfgfphbqUC+aqzty+YPQtcFA0bo/CcPtSaWVByYw0+C4xBHRUNsSztomDcDhduXP2XMTWXNqlhJnkMp0BdfweZTPxAax9EPY3WRi0dHMJQxN5o/GLXBtM4QQWYU2czFCnGs59dTiZ/4FfiMhQK7OEY72L28HfsPBwAi9R2VJzmLTGdAj12s0QM74ZJhDYLOZ9/542RZUxIPqIq8ZjqY2ECnKtIWeNrbJHkp8RaeJ1C5i0fxbf+3xxh/trgF3t9NdiJ+4jibQZxtYvgVFsP9u7x+df/FPIhTJiCvVV4GQOHsYGCIyIoDSdrZ2zN3M2ghdp1t4YKN9TU4l/9jN2zMW2gDXTtM8256SJmrysbYRepElHLSgx76vWm8MEScDXc8D7b/9fpGg0JLcTxCZiM+OcLqzP5mH3TBuWjtqSF/u8/VNy5D5jqFmn5UMKZzpsI8TLluiYl7iW6318UL1L8NznpADNOHGWTwbPBTQ9VSPAZ+bpXpTyPC0Qmu0FsIxauSMMu9r53+6WHSoCY7LDzxWXgby7twT32kduYo0O3WZUHFyDN3uR4GG413iKLsQxH3CKcwKCJie09MzlyNlUj75D2VY=
