language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- echo "skipping tests"
deploy:
  provider: pypi
  skip_existing: true
  user: jaj
  password:
    secure: VtrDJ+exm0F8eEHrNF6Fd00KA/an2BCnYvyqrv6DJiY41tkAG4GWfTWPPGb5eIOX4oSi86NEumofpa6uMP0LlfUGYjedFvAZ821oPheSU2lr7HxcES0WDEUQFz3HE9g0POtZ7ILivHBNYsFoyTjuO0GcBMVGufRcQQXuu6jRMnqaYyDVC9wA8lzymkhiEIqpOUN8x3lzvuhgseZ7vP0hkNCQbJTn+uEpOG0+93vNFBKawFxntlXP6+gBCYxqK5UdOTflwU9Bhw+/IT/telmAsAOQ/gbv6nGUHDI+lvk4wZEXQ/fLHgsFcTz0ZrdFcavfkSzPXi6qYxh2beYDkFLPRUJKW88/UjyPFr+bu9wO3GvPd6vrksgApHfY/peUNAA6NmwXeZXWUtCh8uSEih47CsiyjK49h3wbqQOWQJ/L9ESfpKmyVUyQ7iajHuBOYxW6V1zYCXQziWAX+gRfopnkxZqosr8DvmehfWj4oHV2NgVns3PuHrpDOAXlHDUznJvJilrLUF0n2nMOpNAz+OcZ0aU9ewArkmmbZyBbCXaQ2vAZApNJluQLftCW1PJ0jykJ7aRLvFgnIyxMCWqeAujgCC4LrAgKn0sMYhaq0u4l+3PuxK3VBk5ZZNzIo1AJRvP0Etpppl0F8OEofisJMhXcqDa/rwZj+f/wVfLzYcr2zFU=
