version: "~> 1.0"
jobs:
  include:
  - os: linux
    language: python
    python: '3.8'
    install:
    - pip install -r requirements.txt
    script:
    - echo "no tests"
    deploy:
      provider: pypi
      on:
        tags: true
      user: jaj
      password:
        secure: YLdYvwUb02avnnt67IeSUm8C7t3MKzeg/Bd14eXvpNX8VNvtGfmiunEuJfcigtpGCZq4Jzdj+VqTakO+PBNtxPsI0eJKzYvY/t4j8YvU01dwnT/TWYVOwrGAtD2gO+8fUTi7vjWHT3NPQ5SQckrl9y9AoQmg7ui0Ns9U46xqRvgm1dBtDAJWjMl8W1DtGTfa+d90bry4hH4Fdmq6vABwd3cA+hbgTpAhUN1KntTvdgE4KiqXyG0g+ZoJHrh2t4VQ5DK4E8lKgmbjeI2XrJyni2nd7QntDhi5k39M69gMT5reqcRdLwpWVPE99Is0xmmt3XnCz85GWEXw+bYeiDIxn3mlFo6XF6xf3F22WrHO17pzeCGqfdlaU5jLtaQuryxGYggG5cyd1kAi+luK7LXMjN5KqGtrJ8obRhRbN3J+bcGO4BAuQxYiViVHW6PceGxwQSidxTfrzsTxHG3Jn4Phc+bOGn61debiQ3uQt1x+mhPz22qMZlCPUgejysJANK57CHhhcddn++PyzQSxKF+1Ea/RbuIM82qwDXqHl53otJJkN3p81y8FbpbYVKaPr8Psly1uHwoSHFKKHeHB4nEtdANwsDe+kBY/+6FcKWMRWtlhl2Q2ty6MdMfp4zclkUkWqRwUHrK8JPg3+Y4q/LMIUJF3Qa/z15amYg7yfOrkbOw=

  - os: windows
    language: shell
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    before_install:
    - choco install python --version 3.8.2
    - python --version
    - python -m ensurepip
    install:
    - pip install -r requirements.txt
    - pip install pyinstaller
    script:
    - pyinstaller --onefile GraPhysio.spec
    - sleep 1
    - ls -l dist
    deploy:
      provider: releases
      file: dist/GraPhysio.exe
      skip_cleanup: true
      on:
        tags: true
      api_key:
        secure: Haab+3gG/OS3UHiSS87yTuOTH1LFZndeq3DSA1epXazk8MIJm2LmVnupQvsKylRmL2u1W0vGT1VRv+l3iBWVutaKmoRgGRg4GPCog3FeFWt4awzsy7gXryPvjDLaXia3+K0Y5jeuEMZzMxErXKEpn+lBRcsRcFefw0hu1Bz0YPmE+wVAm/b82b0Q7Z7+NRjC0sF1Sb4jJc+22gSRr1qG2swGj5ihNcwA/ntYVw4ZIJ/drYT7a4++rm8AOS1Lr33T9mGz78PFB0c175ykHP20Z2bM4+R9Qrpu1CRmDXDhBSpZ/noq0evOcrZKiU3S627ukJNsuEQfJuq48Eb/+fF1FwifnqYEx8icTczgLzBCJ+e6fdHSrMmZy975B5wgrzt+zmWQjbdn2zIv49/eIiqy7pUr4MmQB7CiI7uJK3k4reI8L6Bmq77PQuUQIS/ZnvnXlC/R6zEZ/3zJTVs0QnTWHH3tpP/hUPVS1EQopqqz4WWZ0AJ+EdH42YfztdQvG8frU8njMsg31c+TVZLnHlXHuCq1NpzSKOo59dkrcGqJ6CKYUewfF/Xr+B8rZ8Ui7Ua7PnAHJPQKa407n0FESJfV8aHKTupnHCEJ4jDPTSlBCq0SEjMwDxlUHg0bCLLxY8IweYbt25n5ICmUrGHVazN8MGxpfKA9WbrmgLvT3tkzz8M=
