version: ~> 1.0

jobs:
  include:
    - os: linux
      language: python
      python: '3.8'
      env: BUILD_BRANCH=pypi
    - os: windows
      language: shell
      env: BUILD_BRANCH=winexe

import:
  - source: .travis/pypi.yml
    if: env(BUILD_BRANCH) = pypi
  - source: .travis/winexe.yml
    if: env(BUILD_BRANCH) = winexe
