version: ~> 1.0

jobs:
  include:
    - os: linux
      language: python
      python: '3.8'
    - os: windows
      language: shell

import:
  - source: .travis/pypi.yml
    if: os = linux
  - source: .travis/winexe.yml
    if: os = windows
