version: ~> 1.0

matrix:
  include:
    - language: shell
      import:
        - source: .travis/win_exe.yml
          if: os = windows
    - language: python
      import:
        - source: .travis/pypi.yml
          if: os = linux
