language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- echo "skipping tests"
deploy:
  provider: pypi
  skip_existing: true
  user: "jaj"
  password:
    secure: "IFluHSSBIuyTEf2r4fh8cCA7Kn45rfW2U6WZdPl8lx1L9I1cDnc1T7M4rkuPNqbgU6ifVjuN/UnyWDX24ac5HSV672n3ChJzCIbdkysadA1l/O78ct101raCE9Ia0KyoCTYL5OZ0LSwHlw+aKVRknxk7ktbzqlFZdcak/OsCws8JcIXrV0Zib+N8FMCmNsRtRloeCweqFmfWyYfDHaayitx2c+oi/QTiQgrcBpYdg1gd9yOV+1PER4+yw8OAFz8MdDC4NgRq3AZ2Gc4B24plsUmcUQxRHHXKxobMHIg8aDuaW86OIJ0kfpqC4LqTDn4azstO/zW/sdon5g2SJD6T1pDT2eG2ntzpNS3RGEXxwFEEydkhQ1mLOW+uWVEOQDr9/dW0fcKxObjpT8aCOuo/xXNWkuBNOP6to1ZuAuNVCKhTnkGijvil6JgrkvzOsDl3rvyltBh+70xRKYvuyvfSt1vxBsNebhKnQ6OHdqUjeK4xy2DgcOKkIASSv932k+g8Z6lLgvs87DsCoTRRdwz488DLglIdg+eNEcxZsPxCm3blmu/qybt9qbJRVmqeaCVWd1u0z9hh7BK2aC2YRq1WqH8T7uVjAyeP0LPHCGiayGzCFp0RwCCfC5vYZ5xS0+md50kBJKIIuJPHGC5azKau0vR+xEzzKU2CYgAUir5V9Mk="
