version: ~> 1.0

jobs:
  include:
    - os: linux
      language: python
      python: '3.8'
    - os: windows
      language: shell

import:
  - source: jaj42/GraPhysio:.travis/pypi.yml@master
    if: os = linux
  - source: jaj42/GraPhysio:.travis/winexe.yml@master
    if: os = windows
