# Form implementation generated from reading ui file 'setuppuloop.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from pyqtgraph import QtCore, QtGui, QtWidgets


class Ui_SetupPULoop(object):
    def setupUi(self, SetupPULoop):
        SetupPULoop.setObjectName("SetupPULoop")
        SetupPULoop.resize(387, 371)
        self.verticalLayout = QtWidgets.QVBoxLayout(SetupPULoop)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(parent=SetupPULoop)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.comboU = QtWidgets.QComboBox(parent=SetupPULoop)
        self.comboU.setObjectName("comboU")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboU)
        self.label_2 = QtWidgets.QLabel(parent=SetupPULoop)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.comboP = QtWidgets.QComboBox(parent=SetupPULoop)
        self.comboP.setObjectName("comboP")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboP)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(parent=SetupPULoop)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(parent=SetupPULoop)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SetupPULoop)
        QtCore.QMetaObject.connectSlotsByName(SetupPULoop)

    def retranslateUi(self, SetupPULoop):
        _translate = QtCore.QCoreApplication.translate
        SetupPULoop.setWindowTitle(_translate("SetupPULoop", "Set up PU-Loop"))
        self.label.setText(_translate("SetupPULoop", "Velocity (U)"))
        self.label_2.setText(_translate("SetupPULoop", "Pressure (P)"))
        self.okButton.setText(_translate("SetupPULoop", "Ok"))
        self.cancelButton.setText(_translate("SetupPULoop", "Cancel"))
