# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/newplot.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewPlot(object):
    def setupUi(self, NewPlot):
        NewPlot.setObjectName(_fromUtf8("NewPlot"))
        NewPlot.resize(512, 556)
        NewPlot.setSizeGripEnabled(False)
        self.btnCancel = QtGui.QPushButton(NewPlot)
        self.btnCancel.setGeometry(QtCore.QRect(270, 510, 91, 31))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.btnOk = QtGui.QPushButton(NewPlot)
        self.btnOk.setGeometry(QtCore.QRect(150, 510, 91, 31))
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.frame = QtGui.QFrame(NewPlot)
        self.frame.setGeometry(QtCore.QRect(10, 10, 481, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 58, 14))
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 27, 461, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txtFile = QtGui.QLineEdit(self.layoutWidget)
        self.txtFile.setObjectName(_fromUtf8("txtFile"))
        self.horizontalLayout.addWidget(self.txtFile)
        self.btnBrowse = QtGui.QPushButton(self.layoutWidget)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.frame_3 = QtGui.QFrame(NewPlot)
        self.frame_3.setGeometry(QtCore.QRect(260, 300, 231, 191))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.btnRemoveY = QtGui.QPushButton(self.frame_3)
        self.btnRemoveY.setGeometry(QtCore.QRect(140, 160, 79, 24))
        self.btnRemoveY.setObjectName(_fromUtf8("btnRemoveY"))
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lstVY = QtGui.QListView(self.frame_3)
        self.lstVY.setGeometry(QtCore.QRect(10, 30, 211, 121))
        self.lstVY.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lstVY.setObjectName(_fromUtf8("lstVY"))
        self.btnRemoveY.raise_()
        self.label_5.raise_()
        self.lstVY.raise_()
        self.frame_2 = QtGui.QFrame(NewPlot)
        self.frame_2.setGeometry(QtCore.QRect(10, 300, 241, 191))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.btnRemoveX = QtGui.QPushButton(self.frame_2)
        self.btnRemoveX.setGeometry(QtCore.QRect(150, 160, 79, 24))
        self.btnRemoveX.setObjectName(_fromUtf8("btnRemoveX"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lstVX = QtGui.QListView(self.frame_2)
        self.lstVX.setGeometry(QtCore.QRect(10, 30, 211, 121))
        self.lstVX.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lstVX.setObjectName(_fromUtf8("lstVX"))
        self.frame_4 = QtGui.QFrame(NewPlot)
        self.frame_4.setGeometry(QtCore.QRect(260, 90, 231, 191))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_6 = QtGui.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.btnToY = QtGui.QPushButton(self.frame_4)
        self.btnToY.setGeometry(QtCore.QRect(140, 160, 79, 24))
        self.btnToY.setObjectName(_fromUtf8("btnToY"))
        self.btnToX = QtGui.QPushButton(self.frame_4)
        self.btnToX.setGeometry(QtCore.QRect(10, 160, 79, 24))
        self.btnToX.setObjectName(_fromUtf8("btnToX"))
        self.lstVAll = QtGui.QListView(self.frame_4)
        self.lstVAll.setGeometry(QtCore.QRect(10, 30, 211, 121))
        self.lstVAll.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lstVAll.setObjectName(_fromUtf8("lstVAll"))
        self.btnLoad = QtGui.QPushButton(NewPlot)
        self.btnLoad.setGeometry(QtCore.QRect(80, 250, 91, 31))
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))
        self.layoutWidget1 = QtGui.QWidget(NewPlot)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 90, 211, 61))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txtDecimal = QtGui.QComboBox(self.layoutWidget1)
        self.txtDecimal.setEditable(True)
        self.txtDecimal.setObjectName(_fromUtf8("txtDecimal"))
        self.txtDecimal.addItem(_fromUtf8(""))
        self.txtDecimal.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.txtDecimal, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.txtSep = QtGui.QComboBox(self.layoutWidget1)
        self.txtSep.setEditable(True)
        self.txtSep.setObjectName(_fromUtf8("txtSep"))
        self.txtSep.addItem(_fromUtf8(""))
        self.txtSep.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.txtSep, 0, 1, 1, 1)
        self.gridLayoutWidget = QtGui.QWidget(NewPlot)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 160, 231, 81))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chkUnixTime = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkUnixTime.setObjectName(_fromUtf8("chkUnixTime"))
        self.gridLayout_2.addWidget(self.chkUnixTime, 2, 0, 1, 1)
        self.txtDateTime = QtGui.QComboBox(self.gridLayoutWidget)
        self.txtDateTime.setEditable(True)
        self.txtDateTime.setObjectName(_fromUtf8("txtDateTime"))
        self.txtDateTime.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.txtDateTime, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.layoutWidget.raise_()
        self.btnCancel.raise_()
        self.btnOk.raise_()
        self.frame.raise_()
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame_4.raise_()
        self.btnLoad.raise_()
        self.gridLayoutWidget.raise_()
        self.label_7.raise_()

        self.retranslateUi(NewPlot)
        QtCore.QMetaObject.connectSlotsByName(NewPlot)

    def retranslateUi(self, NewPlot):
        NewPlot.setWindowTitle(_translate("NewPlot", "New Plot", None))
        self.btnCancel.setText(_translate("NewPlot", "Cancel", None))
        self.btnOk.setText(_translate("NewPlot", "OK", None))
        self.label_3.setText(_translate("NewPlot", "Open File", None))
        self.btnBrowse.setText(_translate("NewPlot", "Browse", None))
        self.btnRemoveY.setText(_translate("NewPlot", "Remove", None))
        self.label_5.setText(_translate("NewPlot", "Elements on Y axis", None))
        self.btnRemoveX.setText(_translate("NewPlot", "Remove", None))
        self.label_4.setText(_translate("NewPlot", "Elements on X axis", None))
        self.label_6.setText(_translate("NewPlot", "Loaded Fields", None))
        self.btnToY.setText(_translate("NewPlot", "Move to Y", None))
        self.btnToX.setText(_translate("NewPlot", "Move to X", None))
        self.btnLoad.setText(_translate("NewPlot", "Load", None))
        self.txtDecimal.setItemText(0, _translate("NewPlot", ".", None))
        self.txtDecimal.setItemText(1, _translate("NewPlot", ",", None))
        self.label_2.setText(_translate("NewPlot", "Field Seperator", None))
        self.label.setText(_translate("NewPlot", "Decimal seperator", None))
        self.txtSep.setItemText(0, _translate("NewPlot", ",", None))
        self.txtSep.setItemText(1, _translate("NewPlot", ";", None))
        self.chkUnixTime.setText(_translate("NewPlot", "Unix Timestamp", None))
        self.txtDateTime.setItemText(0, _translate("NewPlot", "%Y-%m-%d %H:%M:%S,%f", None))
        self.label_7.setText(_translate("NewPlot", "Date/Time Format", None))

